### ISSUE TITLE
v1.1.0 still uses `set-output` which will be disabled on 31st May 2023

### ISSUE THREAD

**Issue by gligoran** [DopplerHQ/secrets-fetch-action#10]
The 31st of May 2023, when the `set-output` command is going to get disabled is getting near. I can see that you already resolved this in the latest commits, but the current 1.1.0 release, still has this problem. Any plans to release a new version?

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by nmanoogian** [comment]
Thanks for the reminder, @gligoran! We've just released [v1.1.1](https://github.com/DopplerHQ/secrets-fetch-action/releases/tag/v1.1.1) with the updates to the `@actions/core` lib.

Please let me know if you run into any issues!

**Comment by boedy** [comment]
The readme is still pointing towards the 1.1.0 release. New users (including me) will still install the 1.1.0 version.

**Comment by Piccirello** [comment]
Thanks for pointing that out! Fixed in https://github.com/DopplerHQ/secrets-fetch-action/pull/11
