### ISSUE TITLE
Required update to Node.js 20 following deprecation warning

### ISSUE THREAD

**Issue by glarivie** [DopplerHQ/secrets-fetch-action#14]
I've encountered a deprecation warning while using the `dopplerhq/secrets-fetch-action@v1.1.2` action. The warning states that Node.js 16 actions are deprecated, and it recommends an update to Node.js 20. Here's the warning message I received:

```
Node.js 16 actions are deprecated.
Please update the following actions to use Node.js 20: dopplerhq/secrets-fetch-action@v1.1.2.
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

The files that seem to be affected are:
 - https://github.com/DopplerHQ/secrets-fetch-action/blob/main/.github/workflows/test.yml#L12
 - https://github.com/DopplerHQ/secrets-fetch-action/blob/main/action.yml#L25

**Comment by nmanoogian** [comment]
Thanks for letting us know about this! We're tracking this internally under ENG-7523. I'll follow up once we've updated to Node 20.
