### ISSUE TITLE
Feature Request: Skip `setSecret` for unmasked values

### ISSUE THREAD

**Issue by drewfradette** [DopplerHQ/secrets-fetch-action#16]
Hello Doppler friends!

I am in the process of moving some CI workflows to Github Actions and like the simplicity of this action vs installing & running doppler run in CI.

But, we use Doppler as a general configuration management tool (as outlined in the [Doppler docs here](https://docs.doppler.com/docs/secret-visibility)). This means we have values like `NODE_ENV=test` in Doppler. When these are pulled in, we get rather silly output such as:

```
Starting "rush ci:***"
Analyzing repo state... DONE (0.***8 seconds)
```

Would it be possible for y'all to to skip the core.setSecret call for values that are unmasked? Even adding this as an optional input parameter so we can decide would be awesome.

**Comment by nmanoogian** [comment]
Thanks for calling this out, @drewfradette! That masking for unmasked secret values is silly indeed. We're tracking this internally under ENG-7621 and we'll keep this issue updated.

**Comment by nmanoogian** [comment]
(PS: Sorry for the description thrashing! Our issue tracker apparently syncs the description of the internal issue with the GitHub Issue)

**Comment by drewfradette** [comment]
Hey @nmanoogian, that's awesome, thanks! 

(Also, please let watsonian know Drew says hello; we use to work together at Heroku)

**Comment by nmanoogian** [comment]
Will do!

**Comment by watsonian** [comment]
@drewfradette 👋

**Comment by drewfradette** [comment]
Hey @nmanoogian & @watsonian,
  One of my teammates took a pass at this in #17 if y'all are interested.

**Comment by nmanoogian** [comment]
Awesome, thanks! We'll have a look
